"""Add alerts column

Revision ID: 04cc906629ee
Revises: e361181010a6
Create Date: 2025-11-08 15:19:05.356673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04cc906629ee'
down_revision: Union[str, None] = 'e361181010a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_settings', sa.Column('alerts', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_settings', 'alerts')
    # ### end Alembic commands ###
