"""Add barcodes table

Revision ID: 2f4755a3fa3f
Revises: 4b373ef6e871
Create Date: 2025-11-26 12:03:46.657007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f4755a3fa3f'
down_revision: Union[str, None] = '4b373ef6e871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barcodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('sku_code', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('barcode_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_code', 'org_id'], ['skus.code', 'skus.org_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'value', name='uq_barcodes_org_value')
    )
    op.create_index('ix_barcodes_lookup', 'barcodes', ['org_id', 'value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_barcodes_lookup', table_name='barcodes')
    op.drop_table('barcodes')
    # ### end Alembic commands ###
