"""Move alerts and threshold settings to SKU table

Revision ID: 42b6085e1bea
Revises: 04cc906629ee
Create Date: 2025-11-09 12:30:25.190756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b6085e1bea'
down_revision: Union[str, None] = '04cc906629ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_settings', 'low_stock_threshold')
    op.drop_column('org_settings', 'reorder_point')
    op.add_column('skus', sa.Column('alerts', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('skus', sa.Column('low_stock_threshold', sa.Integer(), server_default='10', nullable=False))
    op.add_column('skus', sa.Column('reorder_point', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'reorder_point')
    op.drop_column('skus', 'low_stock_threshold')
    op.drop_column('skus', 'alerts')
    op.add_column('org_settings', sa.Column('reorder_point', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=False))
    op.add_column('org_settings', sa.Column('low_stock_threshold', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
