"""Add alerts models

Revision ID: 45ea3afa6267
Revises: bc0a0d79d131
Create Date: 2025-11-12 19:42:39.126420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45ea3afa6267'
down_revision: Union[str, None] = 'bc0a0d79d131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('aggregation_key', sa.String(), nullable=True),
    sa.Column('alert_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_aggregation_key'), 'alerts', ['aggregation_key'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_org_aggregation', 'alerts', ['org_id', 'aggregation_key'], unique=False)
    op.create_index(op.f('ix_alerts_org_id'), 'alerts', ['org_id'], unique=False)
    op.create_index('ix_alerts_org_type_created', 'alerts', ['org_id', 'alert_type', 'created_at'], unique=False)
    op.create_table('alert_read_receipts',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', 'user_id')
    )
    op.create_index('ix_alert_receipts_user_alert', 'alert_read_receipts', ['user_id', 'alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_receipts_user_alert', table_name='alert_read_receipts')
    op.drop_table('alert_read_receipts')
    op.drop_index('ix_alerts_org_type_created', table_name='alerts')
    op.drop_index(op.f('ix_alerts_org_id'), table_name='alerts')
    op.drop_index('ix_alerts_org_aggregation', table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_aggregation_key'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
