"""Add qty_before to transactions and product_name, created_at to inventory state

Revision ID: 45f96938450a
Revises: 49b7d4453c92
Create Date: 2025-10-03 16:33:17.213026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f96938450a'
down_revision: Union[str, None] = '49b7d4453c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_state', sa.Column('product_name', sa.String(), nullable=False))
    op.add_column('inventory_state', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('inventory_txn', sa.Column('qty_before', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_txn', 'qty_before')
    op.drop_column('inventory_state', 'created_at')
    op.drop_column('inventory_state', 'product_name')
    # ### end Alembic commands ###
