"""Rename type to format

Revision ID: 48060c37e1e1
Revises: 2f4755a3fa3f
Create Date: 2025-11-26 18:51:09.146297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48060c37e1e1'
down_revision: Union[str, None] = '2f4755a3fa3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barcodes', sa.Column('barcode_format', sa.String(), nullable=False))
    op.drop_column('barcodes', 'barcode_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barcodes', sa.Column('barcode_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('barcodes', 'barcode_format')
    # ### end Alembic commands ###
