"""Add Location model

Revision ID: 49b7d4453c92
Revises: fddc6e4ab0a5
Create Date: 2025-09-22 12:30:42.569220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b7d4453c92'
down_revision: Union[str, None] = 'fddc6e4ab0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=True)
    op.create_index(op.f('ix_inventory_state_location_id'), 'inventory_state', ['location_id'], unique=False)
    op.create_foreign_key(None, 'inventory_state', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(None, 'inventory_txn', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(None, 'reservations', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(None, 'serials', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serials', type_='foreignkey')
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_constraint(None, 'inventory_txn', type_='foreignkey')
    op.drop_constraint(None, 'inventory_state', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_state_location_id'), table_name='inventory_state')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
