"""Stop enforcing org name uniqueness

Revision ID: 4b373ef6e871
Revises: 45ea3afa6267
Create Date: 2025-11-25 12:35:09.732241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b373ef6e871'
down_revision: Union[str, None] = '45ea3afa6267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orgs_name_key'), 'orgs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('orgs_name_key'), 'orgs', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
