"""Add billing frequency to Subscription model

Revision ID: 76ea657079db
Revises: 6119b0121c83
Create Date: 2025-11-05 11:27:53.602249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ea657079db'
down_revision: Union[str, None] = '6119b0121c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('billing_frequency', sa.String(), server_default='monthly', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'billing_frequency')
    # ### end Alembic commands ###
