"""Add stock threshold defaults to org settings

Revision ID: bc0a0d79d131
Revises: 42b6085e1bea
Create Date: 2025-11-12 12:26:44.746483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0a0d79d131'
down_revision: Union[str, None] = '42b6085e1bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_settings', sa.Column('default_reorder_point', sa.Integer(), nullable=True))
    op.add_column('org_settings', sa.Column('default_low_stock_threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_settings', 'default_low_stock_threshold')
    op.drop_column('org_settings', 'default_reorder_point')
    # ### end Alembic commands ###
