"""Initial migration

Revision ID: c40961ea7828
Revises: 
Create Date: 2025-09-17 19:37:14.710511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40961ea7828'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_state',
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('sku_id', 'location_id')
    )
    op.create_table('inventory_txn',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('txn_metadata', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_txn_location_id'), 'inventory_txn', ['location_id'], unique=False)
    op.create_index(op.f('ix_inventory_txn_sku_id'), 'inventory_txn', ['sku_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'sku_id', 'location_id', name='uq_order_sku_loc')
    )
    op.create_index(op.f('ix_reservations_location_id'), 'reservations', ['location_id'], unique=False)
    op.create_index(op.f('ix_reservations_order_id'), 'reservations', ['order_id'], unique=False)
    op.create_index(op.f('ix_reservations_sku_id'), 'reservations', ['sku_id'], unique=False)
    op.create_table('serials',
    sa.Column('serial', sa.String(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_tx_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['current_tx_id'], ['inventory_txn.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('serial')
    )
    op.create_index(op.f('ix_serials_location_id'), 'serials', ['location_id'], unique=False)
    op.create_index(op.f('ix_serials_sku_id'), 'serials', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serials_sku_id'), table_name='serials')
    op.drop_index(op.f('ix_serials_location_id'), table_name='serials')
    op.drop_table('serials')
    op.drop_index(op.f('ix_reservations_sku_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_order_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_location_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_inventory_txn_sku_id'), table_name='inventory_txn')
    op.drop_index(op.f('ix_inventory_txn_location_id'), table_name='inventory_txn')
    op.drop_table('inventory_txn')
    op.drop_table('inventory_state')
    # ### end Alembic commands ###
