"""Remove first and last name from Nooryx admins table

Revision ID: c9e8b8a30dc1
Revises: a4c71af01683
Create Date: 2025-12-29 14:46:53.095200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e8b8a30dc1'
down_revision: Union[str, None] = 'a4c71af01683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nooryx_admins', 'first_name')
    op.drop_column('nooryx_admins', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nooryx_admins', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('nooryx_admins', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
