"""Revert refresh token relationship

Revision ID: cfe805b3c7fc
Revises: 2e2e110f531f
Create Date: 2025-11-05 12:38:10.647560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe805b3c7fc'
down_revision: Union[str, None] = '2e2e110f531f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
