"""Add server defaults

Revision ID: e361181010a6
Revises: 2e2e110f531f
Create Date: 2025-11-05 13:10:26.963259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e361181010a6'
down_revision: Union[str, None] = '2e2e110f531f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('org_settings', 'low_stock_threshold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('org_settings', 'reorder_point',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('user_settings', 'locale',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_settings', 'pagination',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_settings', 'date_format',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_settings', 'date_format',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_settings', 'pagination',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_settings', 'locale',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('org_settings', 'reorder_point',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('org_settings', 'low_stock_threshold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    # ### end Alembic commands ###
