"""Make alerts settings flag user-scoped instead of being org-wide

Revision ID: f0a54d6565f7
Revises: fd968e9c988a
Create Date: 2025-12-16 11:54:38.972409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a54d6565f7'
down_revision: Union[str, None] = 'fd968e9c988a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_settings', 'alerts')
    op.add_column('user_settings', sa.Column('alerts', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'alerts')
    op.add_column('org_settings', sa.Column('alerts', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
